apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "httpd-example", "namespace": "development", "kind":
      "DeploymentConfig"}]'
  creationTimestamp: null
  labels:
    app: jenkins-pipeline-development
    name: development-pipeline
    template: application-template-development-pipeline
  name: development-pipeline
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: git
    git:
      uri: https://github.com/wanderboessenkool/cicd-demo.git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: pipelines/Jenkinsfile
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
status:
  lastVersion: 0
