node('maven') {
  stage ('build') {
    openshiftBuild(buildConfig: 'httpd-example', showBuildLogs: 'true', namespace: 'development')
  }
  stage ('deploy') {
    openshiftDeploy(deploymentConfig: 'httpd-example', namespace: 'development')
  }
}
stage('apprval') {
  input('Proceed with deploy to testing?')
}
node('maven') {
  stage ('tag') {
    openshiftTag(namespace: 'development', sourceStream: 'httpd-example', sourceTag: 'latest', destinationNamespace: 'testing', destinationStream: 'httpd-example', destinationTag: 'latest')
  }
  stage ('deploy') {
    openshiftDeploy(deploymentConfig: 'httpd-example', namespace: 'testing')
  }
}

